name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Heroku credentials
        env: 
          HEROKU_LOGIN: ${{secrets.HEROKU_LOGIN}}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          cat >~/.netrc <<EOF
          machine git.heroku.com
            login $HEROKU_LOGIN
            password $HEROKU_API_KEY
          EOF
      - name: Push to Heroku
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku git:remote -a gwwc-data-table-datagrid
          git show-ref
          git push heroku refs/remotes/origin/main:refs/heads/main